Simplify tautologies
blyxxyz/python-nnf pull request #29
Opened 2022-12-09 02:52 UTC by haz

Idea is to allow for tautologies in `to_CNF` conversions so that model counts aren't thrown off (variables mentioned in a tautological clause will be missing from the compilation).

2022-12-09 02:56 UTC, haz commented
Closes #30

2022-12-09 16:43 UTC, blyxxyz approved these changes
LGTM.

Another solution might be to give `.model_count()` a `names` argument so it can adjust for excluded names. But this is simpler and more broadly useful.

You could add a hypothesis test case that runs `.to_CNF(simplify_tautologies=False)` and checks that no names were lost.

2022-12-09 19:18 UTC, haz commented
Great idea! It caught a corner case where `(x & ~x) | y` was being simplified to just `y`. Can you have another look after the latest commit?

2022-12-09 20:27 UTC, blyxxyz commented
Ah! I hadn't spotted that.

My only concern now is that the name `simplify_tautologies` is inaccurate because it also covers contradictions.

2022-12-10 01:20 UTC, haz commented
Ah, right. Just `simplify` work?

2022-12-11 19:11 UTC, blyxxyz requested changes

2022-12-11 19:11 UTC, blyxxyz commented on nnf/tseitin.py
> +    :param simplify: If True, remove clauses that are always true.
```suggestion
    :param simplify: If True, simplify clauses even if that means eliminating
                     variables.
```
This clarifies why you'd want it to be `False`.

2022-12-12 02:51 UTC, haz commented
Thanks, @blyxxyz ! Should be all set to go if you want to approve/merge.

2022-12-12 05:15 UTC, blyxxyz approved these changes
Looks good! Thanks for bearing with me.

2022-12-12 05:50 UTC, merged